server {
    listen 80;

    # Confiiguração frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy para o backend
    location /api {
        proxy_pass http://backend_app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
